//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bstm.DirectoryServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bstm.DirectoryServices.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; can not be converted to valid AdsPath instance..
        /// </summary>
        internal static string AdsPath_ArgumentOutOfRangeException_InvalidParseValue {
            get {
                return ResourceManager.GetString("AdsPath_ArgumentOutOfRangeException_InvalidParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; of type &apos;{1}&apos; not suitable to syntax &apos;{2}&apos; of directory property &apos;{3}&apos;..
        /// </summary>
        internal static string DirectoryProperty_DirectoryServicesException_InappropriateDirectoryValue {
            get {
                return ResourceManager.GetString("DirectoryProperty_DirectoryServicesException_InappropriateDirectoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain controller can not be null or white space..
        /// </summary>
        internal static string DirectoryProvider_ArgumentOutOfRangeException_InvalidDomainController {
            get {
                return ResourceManager.GetString("DirectoryProvider_ArgumentOutOfRangeException_InvalidDomainController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ASQ searches asqProperty should have syntax &apos;DNString&apos;..
        /// </summary>
        internal static string DirectoryServicesException_InvalidAsqPropertySyntax {
            get {
                return ResourceManager.GetString("DirectoryServicesException_InvalidAsqPropertySyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied rdn list can not be empty..
        /// </summary>
        internal static string DN_ArgumentOutOfRangeException_EmptyRdnList {
            get {
                return ResourceManager.GetString("DN_ArgumentOutOfRangeException_EmptyRdnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN string can not be null or white space..
        /// </summary>
        internal static string DN_ArgumentOutOfRangeException_InvalidDNValue {
            get {
                return ResourceManager.GetString("DN_ArgumentOutOfRangeException_InvalidDNValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fqdn string can not be null or white space..
        /// </summary>
        internal static string DN_ArgumentOutOfRangeException_InvalidFqdnValue {
            get {
                return ResourceManager.GetString("DN_ArgumentOutOfRangeException_InvalidFqdnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; can not be converted to valid DN instance..
        /// </summary>
        internal static string DN_ArgumentOutOfRangeException_InvalidParseValue {
            get {
                return ResourceManager.GetString("DN_ArgumentOutOfRangeException_InvalidParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rdn sequence &apos;{0}&apos; can not be converted to valid DN instance..
        /// </summary>
        internal static string DN_ArgumentOutOfRangeException_InvalidRdnSequence {
            get {
                return ResourceManager.GetString("DN_ArgumentOutOfRangeException_InvalidRdnSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; can not be converted to valid GuidName instance..
        /// </summary>
        internal static string GuidName_ArgumentOutOfRangeException_InvalidParseValue {
            get {
                return ResourceManager.GetString("GuidName_ArgumentOutOfRangeException_InvalidParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuidName string can not be null or white space..
        /// </summary>
        internal static string GuidName_ArgumentOutOfRangeException_InvalidValue {
            get {
                return ResourceManager.GetString("GuidName_ArgumentOutOfRangeException_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapName string can not be null or white space..
        /// </summary>
        internal static string LdapName_ArgumentOutOfRangeException_InvalidValue {
            get {
                return ResourceManager.GetString("LdapName_ArgumentOutOfRangeException_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; can not be converted to valid Rdn instance..
        /// </summary>
        internal static string Rdn_ArgumentOutOfRangeException_InvalidParseValue {
            get {
                return ResourceManager.GetString("Rdn_ArgumentOutOfRangeException_InvalidParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rdn string can not be null or white space..
        /// </summary>
        internal static string Rdn_ArgumentOutOfRangeException_InvalidValue {
            get {
                return ResourceManager.GetString("Rdn_ArgumentOutOfRangeException_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; can not be converted to valid SidName instance..
        /// </summary>
        internal static string SidName_ArgumentOutOfRangeException_InvalidParseValue {
            get {
                return ResourceManager.GetString("SidName_ArgumentOutOfRangeException_InvalidParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SidName string can not be null or white space..
        /// </summary>
        internal static string SidName_ArgumentOutOfRangeException_InvalidValue {
            get {
                return ResourceManager.GetString("SidName_ArgumentOutOfRangeException_InvalidValue", resourceCulture);
            }
        }
    }
}
